baseurl: /tirana
permalink: pretty
future: true
markdown: kramdown
paginate: 5
repo: tirana
github_org: maptime
maptime:
  chapter: Maptime Tirana
  #twitter: TwitterHandle
  #disqus: YOUR DISQUS USERNAME

gems:
  - jekyll-feed
